[package]
name = "sugars_macros"
version.workspace = true
edition.workspace = true
description = "Procedural macros for array tuple syntax and builder patterns"
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
documentation = "https://docs.rs/sugars_macros"
keywords = ["rust", "macros", "proc-macro", "builder", "cyrup"]
categories = ["development-tools::procedural-macro-helpers"]
readme = "../../README.md"

[lib]
path = "src/lib.rs"
proc-macro = true

[dependencies]
hashbrown = { version = "0.15", features = ["serde"] }
# workspace-hack = { version = "0.2.0", path = "../../workspace-hack" }
syn = { version = "2.0", features = ["full", "extra-traits"] }
quote = "1.0"
proc-macro2 = "1.0"

[features]
default = []
