[package]
name = "sugars_macros"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"
proc-macro = true

[dependencies]
hashbrown = { version = "0.15.4", features = ["serde"] }
workspace-hack = { version = "0.1", path = "../../workspace-hack" }
syn = { version = "2.0", features = ["full", "extra-traits"] }
quote = "1.0"
proc-macro2 = "1.0"

[features]
default = []
