[package]
name = "cyrup_release"
version.workspace = true
edition.workspace = true
description = "Production-quality release management for Rust workspaces"
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
documentation = "https://docs.rs/cyrup_release"
keywords = ["rust", "release", "workspace", "publishing", "automation"]
categories = ["development-tools", "command-line-utilities"]
readme = "../../README.md"

[[bin]]
name = "cyrup_release"
path = "src/main.rs"

[lib]
name = "cyrup_release"
path = "src/lib.rs"

[dependencies]
# Git operations using proven kodegen implementation (now in-workspace as packages/gix)
sugars_gix = { path = "../gix" }

# Git operations using pure Rust (no CLI)  
gix = "0.74.0"

# Format-preserving TOML editing
toml_edit = "0.23.3"

# Semantic version parsing and manipulation
semver = { version = "1.0.26", features = ["serde"] }

# CLI argument parsing
clap = { version = "4.5", features = ["derive", "cargo"] }

# Error handling and context
anyhow = "1.0"
thiserror = "2.0"

# Async runtime for process execution
tokio = { version = "1.47", features = ["full"] }
async-trait = "0.1"

# JSON serialization for state persistence
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Date and time handling for state tracking
chrono = { version = "0.4", features = ["serde"] }

# Dependency graph analysis
petgraph = "0.6"
fixedbitset = "0.4"

# TOML parsing and manipulation
toml = "0.8"

# Process execution
which = "7.0"

# Logging
log = "0.4"
env_logger = "0.11"

# Path utilities
path-absolutize = "3.1"

# Workspace integration 
sugars_collections = { version = "0.5.2", path = "../collections" }

[dev-dependencies]
tempfile = "3.14"
assert_cmd = "2.0"
predicates = "3.1"
