[package]
name = "cyrup_sugars"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Main crate providing syntactic sugar and utilities for Rust development"
homepage.workspace = true
repository.workspace = true
documentation = "https://docs.rs/cyrup_sugars"
license.workspace = true
keywords.workspace = true
categories = ["development-tools", "data-structures"]
readme = "../../README.md"

[lib]
name = "cyrup_sugars"
path = "src/lib.rs"

[features]
default = ["tokio-async"]
all = ["tokio-async", "std-async", "crossbeam-async", "array-tuples"]
tokio-async = ["tokio", "futures", "parking_lot", "sugars_async_task/tokio", "sugars_async_stream/tokio-backend"]
std-async = ["futures", "async-channel", "sugars_async_stream/std-backend"]
crossbeam-async = ["crossbeam", "futures", "async-channel", "sugars_async_stream/crossbeam-backend"]
array-tuples = ["sugars_collections/array-tuples"]

[dependencies]
sugars_collections = { version = "0.5.3", path = "../collections" }
sugars_async_task = { version = "0.5.3", path = "../async_task" }
sugars_async_stream = { version = "0.5.3", path = "../async_stream" }
sugars_macros = { version = "0.5.3", path = "../macros" }
sugars_gix = { version = "0.5.3", path = "../gix" }
sugars_builders = { version = "0.5.3", path = "../builders" }
serde = { version = "1.0.219", features = ["derive"], optional = true }
serde_json = { version = "1", optional = true }
hashbrown = { version = "0.15", features = ["serde"], optional = true }
gix-hash = { version = "0.19.0", optional = true }
tokio = { version = "1", features = ["rt", "sync", "macros"], optional = true }
futures = { version = "0.3.31", optional = true }
parking_lot = { version = "0.12.4", optional = true }
crossbeam = { version = "0.8.4", optional = true }
async-channel = { version = "2.5.0", optional = true }
# workspace-hack = { version = "0.2.0", path = "../../workspace-hack" }

[dev-dependencies]
tokio = { version = "1", features = ["full", "test-util"] }
tokio-test = "0.4.4"
criterion = "0.7"
proptest = "1.7.0"
pretty_assertions = "1.4.1"
serde_json = "1"
