//! Workspace hack crate managed by cargo-hakari
//!
//! This crate is automatically managed by cargo-hakari and unifies features
//! and optional dependencies across the workspace to optimize build times.
//!
//! DO NOT EDIT THIS FILE MANUALLY. It will be overwritten by cargo-hakari.
//!
//! To update the contents of this file:
//! 1. Edit dependencies in your workspace crates as normal
//! 2. Run: cargo hakari generate

#![allow(dead_code)]

// Empty module to satisfy Rust compiler
#[doc(hidden)]
mod workspace_hack {}
