[package]
name = "sugars_builders"
version.workspace = true
edition.workspace = true
description = "Builder pattern utilities and abstractions for the cyrup-sugars ecosystem"
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
documentation = "https://docs.rs/sugars_builders"
keywords = ["rust", "builder", "pattern", "utilities", "cyrup"]
categories = ["development-tools", "data-structures"]
readme = "../../README.md"

[lib]
path = "src/lib.rs"

[dependencies]
sugars_collections = { version = "0.5.2", path = "../collections" }
sugars_async_task = { version = "0.5.2", path = "../async_task" }
sugars_macros = { version = "0.5.2", path = "../macros" }
hashbrown = { version = "0.15.4", features = ["serde"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = { version = "1.0.140" }
# workspace-hack = { version = "0.2.0", path = "../../workspace-hack" }

[features]
default = []
array-tuples = ["sugars_collections/array-tuples"]
