[package]
name = "sugars_collections"
version.workspace = true
edition.workspace = true
description = "Efficient collection types including ZeroOneOrMany and OneOrMany with array tuple syntax support"
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
documentation = "https://docs.rs/sugars_collections"
keywords.workspace = true
categories = ["data-structures", "development-tools"]
readme = "../../README.md"

[lib]
path = "src/lib.rs"
name = "sugars_collections"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = { version = "1" }
hashbrown = { version = "0.15" }
# workspace-hack = { version = "0.2.0", path = "../../workspace-hack" }

[features]
default = []
array-tuples = []

[dev-dependencies]
pretty_assertions = "1.4.1"
